spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rcs-administrator
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    generate-ddl: false
  liquibase:
    change-log: classpath:liquibase/changelog.yaml
  messages:
    basename: i18n/messages

security:
  enabled: false

language-tag: "ru-RU"