spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rcs-administrator
    username: postgres
    password: 123

  liquibase:
    change-log: classpath:liquibase/changelog.yaml
